### ISSUE TITLE
Build error while running the examples

### ISSUE THREAD

**Issue by talhacali** [krABMaga/krABMaga#30]
While trying to run the examples without visualization with `cargo run --release` command, I am getting following error:

![Screenshot from 2022-05-11 01-04-49](https://user-images.githubusercontent.com/19291415/167729448-20763939-0137-4206-a156-438fc630ef26.png)

As it states, the problem seems to be in `log!` macro.

When I try to run it with visualization with `cargo run --release --features  visualization` command, it works perfectly fine.

Version: 0.1.4
Platform: x86_64, Ubuntu 22.04

**Comment by ddevin96** [comment]
Thank you for reporting. We forgot a mut keyword in the log macro in the 0.1.4 for some edge cases. 
We are fixing it right now, so we are going to release the next version today!
