### ISSUE TITLE
LogTracer error during init()

### ISSUE THREAD

**Issue by cholcombe973** [krABMaga/krABMaga#51]
I'm trying to use latest git version of krabmaga and I'm running into an issue with bevy it looks like:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())', /Users/chholcombe/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_log-0.6.0/src/lib.rs:92:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bd39bbb4bb92df439bf6d85470e296cc6a47ffbd/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/bd39bbb4bb92df439bf6d85470e296cc6a47ffbd/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/bd39bbb4bb92df439bf6d85470e296cc6a47ffbd/library/core/src/result.rs:1790:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/bd39bbb4bb92df439bf6d85470e296cc6a47ffbd/library/core/src/result.rs:1112:23
   4: <bevy_log::LogPlugin as bevy_app::plugin::Plugin>::build
             at /Users/chholcombe/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_log-0.6.0/src/lib.rs:92:9
   5: bevy_app::plugin_group::PluginGroupBuilder::finish
             at /Users/chholcombe/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.6.0/src/plugin_group.rs:118:21
   6: bevy_app::app::App::add_plugins
             at /Users/chholcombe/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.6.0/src/app.rs:797:9
   7: krabmaga::visualization::visualization::Visualization::setup
             at /Users/chholcombe/.cargo/git/checkouts/krabmaga-cbc93ab53f330fa1/19ebdb1/src/visualization/visualization.rs:111:17
   8: krabmaga::visualization::visualization::Visualization::start
             at /Users/chholcombe/.cargo/git/checkouts/krabmaga-cbc93ab53f330fa1/19ebdb1/src/visualization/visualization.rs:78:39
   9: craq_sim::main
             at ./src/main.rs:113:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/bd39bbb4bb92df439bf6d85470e296cc6a47ffbd/library/core/src/ops/function.rs:250:5
```

The krabmaga version I'm using is:
```
[[package]]
name = "krabmaga"
version = "0.2.0"
source = "git+https://github.com/krABMaga/krABMaga#19ebdb1b727a5f51d5d4a0e21333ba26c5038711"
```

I did some lldb debugging and traced this down to the `LogPlugin` in bevy crashing with an `unwrap()` during init. It says that the log was already initialized and can't be done again. I'm not using tracing anywhere else. Just `simple_logger`. 

I made a small patch to the krabmaga source where I just disable the logging plugin and that seems to fix the issue:
```
                app.insert_resource(window_descriptor)
                    .add_plugins_with(DefaultPlugins, |group| group.disable::<LogPlugin>())
                    .add_plugin(EguiPlugin);

```
inside visualization.rs line 114. 
I looked into bevy and it looks like there is 4 newer versions that have been released and one of them fixed this issue with the unwrap. I tried updating the dependency myself in a fork of the krabmaga repo but I'm running into issues with the conditional compilation flags. Would anyone be interested in updating bevy to the latest version on this crate? I think it's pretty far out of sync at this point.

**Comment by ddevin96** [comment]
HI @cholcombe973, which example are you trying to visualize?
I'd like to reproduce the error since it doesn't happen in the test pipeline.
In the meantime, I'm going to release a new version of krABMaga (0.3.0) in the next hours to synchronize the changes we have made in the last few months, so you don't have to rely on the git version. 
We are aware the version of bevy is not updated, and we'll try to migrate to the newest one as soon as possible.

**Comment by cholcombe973** [comment]
Hi @ddevin96 I was trying to do the virus network simulation but modified a little bit for my use case. I just recreated my error using just the bevy library so I think the problem was in my code where I loaded the default plugins twice. 
Thanks for publishing the release!
